[project]
name = "photofield-ai"
version = "0.1.0"
description = " Experimental machine learning API supporting Photofield"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "ftfy>=6.3.1",
    "onnxruntime>=1.22.0,<1.23.0",
    "opencv-python>=4.13.0.90",
    "pillow>=11.2.1",
    "python-multipart>=0.0.20",
    "regex>=2024.11.6",
    "tqdm>=4.67.1",
    "uniface>=3.7.0",
    "uvicorn>=0.34.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "requests>=2.32.5",
]

